services:
  - type: web
    name: animation-auto-engine
    env: node
    plan: free

    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg python3 python3-pip
      pip3 install edge-tts
      npm install

    startCommand: node server.js
